### ISSUE TITLE
Diagrama de Classes

### ISSUE THREAD

**Issue by oliveirafilipe** [Maintenance-of-Votum/Votum#4]
O sistema é desenvolvido em Classes, entretanto não há nenhuma modelagem que apresente as classes e suas interdependencias. 

Seria ideal que tenhamos esse diagrama e que o mesmo seja adicionado na Wiki do projeto

**Comment by arthurhenz** [comment]
Diagrama de classes gerado utilizando uma extensão do VS Code (classdiagram-ts)

![Image](https://user-images.githubusercontent.com/68979925/226760016-1c1f7290-9287-4f82-af37-bad7f257c326.png)

**Comment by arthurhenz** [comment]
Diagrama de classes adicionado no README.md como Pull Request na branch principal do projeto raíz
